name: first hello world
on: [push]
jobs:
    print-hello-world: 
        runs-on: ubuntu-latest
        steps:
            - run: echo hello world
            - run: echo step2
# https://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@github.com/kingkhan404/cicd
